### ISSUE TITLE
data could't be available

### ISSUE THREAD

**Issue by Joe-J** [abhishekdbihani/MudrockNet#2]
I could not download data cause LFS worning.
<img width="563" alt="desc" src="https://user-images.githubusercontent.com/43104448/170852991-72b03b29-5cea-42a3-b6df-2b1adc61f254.png">

**Comment by abhishekdbihani** [comment]
Hi,
It seems the LFS limit has been exceeded due to too many downloads. 

Here is an alternative way to get the code and model:

1. Download code using this command:
`git clone https://github.com/abhishekdbihani/MudrockNet`    

2. Download the trained model from [here:](https://drive.google.com/file/d/1Tx5FdE6P6lsx-myb4uvDV_Mh5h38KQvO/view?usp=sharing) 

Hope this helps!
